# Generated by Django 2.1.3 on 2018-11-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField()),
                ('numero_membros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstiloMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('artista_solo', models.BooleanField()),
                ('bandas', models.ManyToManyField(to='music.Banda')),
            ],
        ),
        migrations.AddField(
            model_name='banda',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.EstiloMusical'),
        ),
    ]
